config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers:{sessions:"admins/sessions"}
  devise_for :users,controllers:{sessions:"users/sessions"}
 resources :posts do
     resources :comments
end
    
root 'posts#index'

end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments, dependent: :destroy
    belongs_to :"user"
    validates_presence_of :user_id
    validates_presence_of :title
    validates_presence_of :body
    validates_length_of :title, :in => 10..50, :message => "el titulo es demasiado corto o largo"
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    before_action :auth_user!
    before_action :set_post, only: [:show, :edit, :update, :destroy]

    def auth_user!
        if admin_signed_in?
            authenticate_admin!
        else
            authenticate_user!
        end
    end

    # GET /posts
    # GET /posts.json
    def index
        if admin_signed_in?
            @posts = Post.all
        else
            @posts = current_user.post
        end
    end

    # GET /posts/1
    # GET /posts/1.json
    def show
    end

    # GET /posts/new
    def new
        if can? :create, Post
            @post = Post.new
        else
            flash[:alert] = "no tiene permisos para agregar un nuevo post"
            redirect_to :action => "index"
        end
    end

    # GET /posts/1/edit
    def edit
        if can? :edit, Post
            @post = Post.edit
        else
            flash[:alert]="no tiene permisos para editar un post"
            redirect_to :action => "index"
        end
    end
    # POST /posts
    # POST /posts.json
    def create
        @post = Post.new(post_params)
        @post.user_id = current_user.id

        respond_to do |format|
            if @post.save
                flash[:success] = "Se guardo correctamente el post."
                format.html { redirect_to @post }
                format.json { render :show, status: :created, location: @post }
            else
                flash[:alert] = "no se pudo guardar el post."
                format.html { render :new }
                format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    # PATCH/PUT /posts/1
    # PATCH/PUT /posts/1.json
    def update
        respond_to do |format|
            if @post.update(post_params)
                format.html { redirect_to @post, notice: 'Post was successfully updated.' }
                format.json { render :show, status: :ok, location: @post }
            else
                format.html { render :edit }
                format.json { render json: @post.errors, status: :unprocessable_entity }
            end
        end
    end

    # DELETE /posts/1
    # DELETE /posts/1.json
    def destroy
        if can? :destroy, Post
            @post.destroy
            respond_to do |format|
                format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
                format.json { head :no_content }
            end
        end
    end

    private
        # Use callbacks to share common setup or constraints between actions.
        def set_post
            @post = Post.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def post_params
            params.require(:post).permit(:title, :body)
        end   
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
<% if @post.errors.any? %>
<div id="error_explanation">
    <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

    <ul>
        <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
    </ul>
</div>
<% end %>

<div class="row">
    <div class="small-6 column">
        <div class="field">
            <%= f.label :title %><br>
            <%= f.text_field :title, :class =>'validate[require,minSize[8]]' %>
        </div>
        <div class="field">
            <%= f.label :body %><br>
            <%= f.text_area :body, :class =>'validate[require,minSize[10]]' %>
        </div>
        <div class="actions">
            <%= f.submit 'Aceptar', :class => 'button small round' %>
        </div>
    </div>
</div>

<% end %>

app/views/posts/_navigation.html.erb
<nav class="top-bar" data-topbar role="navigation">
    <ul class="title-area">
        <li class ="name">
            <h1>Formatos</h1>
        </li>
    </ul>
    <section class="top-bar-section">
        <ul class="left">
            <li class="has-dropdown not-click"> <a href="a">DAC-RG-10</a>
                <ul class="dropdown">
                    <li class="parent-link show-for-small-only"><a class="parent-link-js-generated" href="#">DAC-RG-01</a></li>
                    <li><%= link_to 'Ver', controller: '/posts', action: 'index' %></li>
                    <li><%= link_to 'Nuevo', controller: '/posts', action: 'new'%></li>
                </ul>
            </li>
            
        </ul>
        
        <ul class="right">
            <%if user_signed_in?%>
                <li><a>Logger in as <%= current_user.email%></a></li>
                <li><%= link_to 'edit profile', edit_user_registration_path%></li>
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
            <%elsif admin_signed_in?%>
                <li><a>Logger in as <%= current_admin.email%></a></li>
                <li><%= link_to 'edit profile', edit_user_registration_path%></li>
                <li><%= link_to 'Logout', destroy_user_session_path, method: :delete, :class => 'navbar-link' %></li>
            <%else%>
                <li><%= link_to 'new session', new_user_session_path%></li>
                <li><%= link_to 'new registration', new_user_registration_path%></li>
            <%end%>
            <li class="divider"></li>
        </ul>
    </section>
</nav>


app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
    <thead>
        <tr>
            <!-- <th>Name</th>-->
            <th>Title</th>
            <th>Body</th>
            <th colspan="3"></th>
        </tr>
    </thead>
    
    <tbody>
        <% @posts.each do |post| %>
        <tr>
            <td><%= post.title %></td>
            <td>
                <% if post.body%>
                <a href="#" data-reveal-id="post-<%= post.id%>">Ver mas</a>
                <div id="post-<%=post.id%>" class="reveal-modal" data-reveal>
                    <%=post.body%>
                    <a class="close-reveal-modal">&#215;</a>
                </div>
                <%end%>
            </td>
            <td><%= User.find(post.user_id).email %></td>
            
            <%if can? :show, post %>
            <td><%= link_to 'Show', post %></td>
            <%end%>
            
            <% if can? :edit, post %>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <%end%>
            
            <% if can? :destroy, post %>
            <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
            <%end%>
        </tr>
        <% end %>
    </tbody>
</table>

<br>

<%if user_signed_in? %>
    <%if can? :new, Post%>
        <%= link_to 'New Post', new_post_path %>
    <%end%>
<%end%>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>


<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p>
    <strong>Title:</strong>
    <%=@post.title %>
</p>

<p>
    <strong>Body:</strong>
    <%=@post.body %>
</p>


<div id="comments">
    <%= render :partial => @post.comments.reverse %>
</div>

<%=form_for([@post, Comment.new], remote:true) do |f|%>
<p><%= f.label:body, "New Comment" %><br/>
    <%=f.text_area :body %>
</p>
<p><%=f.submit 'Add Comment', :class => 'button small round'%></p>
<% end %>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>